### ISSUE TITLE
USER STORY : POST

### ISSUE THREAD

**Issue by email2ify** [email2ify/drf_friends#1]
As a **Site User** I can **create comments ** so that **I can manage post**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should be able to create, read, update, and delete  comment to a post
 - **Acceptance Criteria 2**: The site should have character field password for registration
 -  **Acceptance Criteria 3**: The site should have  a comment counts on each post

## Tasks:

- [x] Create a crud function for comment
- [x] Create a place holder for password and username(registration of account in order to comments to a post)
- [x] Test the functionality
